Change ladder URL to coh2.org
Janne252/coh2-replay-discord-bot pull request #11
Opened 2022-07-15 04:51 UTC by mateimarica

The companyofheroes.com ladders were taken down, so the bot's ladder links lead to a 404 page. coh2.org is probably the best alternative.

Eg:

This link is broken
https://www.companyofheroes.com/leaderboards#profile/steam/76561198404414770/standings

This works
https://www.coh2.org/ladders/playercard/steamid/76561198404414770

2022-07-15 05:50 UTC, mateimarica commented
Or maybe coh2stats.com is better

Eg https://coh2stats.com/players/76561198404414770

2022-07-18 14:46 UTC, Janne252 commented
@mateimarica coh2stats.com seems like a better option because it's actively maintained. Will you update the pull request with coh2stats.com URLs?

2022-07-18 14:47 UTC, Janne252 requested changes
Use coh2stats.com as suggested in the comments

2022-08-19 06:23 UTC, Janne252 approved these changes

2022-08-19 06:24 UTC, merged

2022-08-19 06:45 UTC, Janne252 commented
I've requested permission to use `cohstats.com` as the playercard URL on https://github.com/cohstats/coh2stats/issues/244.